export const BUTTON_PRESSED = "@BUTTON_PRESSED";
export const BUTTON_PRESSED_WITH_ZERO = "@BUTTON_PRESSED_WITH_ZERO";

export const EQUAL_PRESSED_START = "@EQUAL_PRESSED_START";
export const EQUAL_PRESSED_SUCCESS = "@EQUAL_PRESSED_SUCCESS";

export const CLEAR_PRESSED = "@CLEAR_PRESSED";

export const NEGATIVE_PRESSED = "@NEGATIVE_PRESSED";

export const PERCENTAGE_PRESSED = "@PERCENTAGE_PRESSED";
